name: riverpod_architecture
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


  # StateManagement
  flutter_riverpod: ^2.4.5
  provider: ^6.0.4

  #Firebase
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.13.0
  firebase_ui_auth: ^1.10.0
  firebase_storage: ^11.5.6



  # responsive
  kartal: ^3.5.0


  equatable: ^2.0.5


  #localDatabase
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.2
  hive_flutter: any


  #utility
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_pdfviewer: ^24.2.4
  o3d: ^3.1.0
  url_launcher: ^6.0.9





  #services
  connectivity_plus: ^5.0.2
  easy_localization: ^3.0.3
  package_info_plus: ^4.2.0
  device_info_plus: ^9.0.3



  #widget
  fluttertoast: ^8.2.4
  flashy_tab_bar2: ^0.0.6
  shaped_bottom_bar: ^1.1.0
  image_picker: ^1.0.5
  sweep_animation_button: ^0.0.3
  flutter_verification_code: ^1.1.7




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_gen: ^4.0.0



dependency_overrides:
  hive: ^3.0.0-dev






# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  generate: true
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/models/
